name: Build WEMU Project

on:
  pull_request:
    branches:
      - dev
      - main
  push:
    branches:
      - 29-github-action-ci-checking-the-cmake-project-itself-is-still-building-as-it-should
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: qtproject/qt:qt6_6.5.0-ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create build directory
        run: mkdir -p build

      - name: Configure project with CMake
        run: |
          cd build
          cmake ..

      - name: Build the project
        run: |
          cd build
          cmake --build .